source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASTimer_Example', :exclusive => true do
  pod "ASTimer", :path => "../"
end

target 'ASTimer_Tests', :exclusive => true do
  pod "ASTimer", :path => "../"

  
end
